#region Utility


function GetBuiltInAdministratorsName() {
    [OutputType([string])]
    param()
    $securityIdentifier = New-Object -TypeName SecurityIdentifier -ArgumentList (
        [WellKnownSidType]::BuiltinAdministratorsSid,
        $null
    )
    $nTAccount = [NTAccount]$securityIdentifier.Translate(
                     [System.Type]::GetType("System.Security.Principal.NTAccount")
                 )
    return $nTAccount.ToString()
}


function GetCurrentUserName() {
    [OutputType([string])]
    param()
    $string = $env:USERNAME
    if ((-not [string]::IsNullOrWhiteSpace($env:USERDOMAIN)) -and
        (-not $env:USERDOMAIN.Equals($env:COMPUTERNAME, [StringComparison]::OrdinalIgnoreCase))) {
            $string = $string + '@' + $env:USERDOMAIN
    }
    return $string
}


#endregion


#region Stubs


function Add-SBHost() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [securestring]
        ${CertificateAutoGenerationKey},

        [Parameter(Mandatory=$true)]
        [ValidateNotNull()]
        [bool]
        ${EnableFirewallRules},

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${ExternalBrokerPort},

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [uri]
        ${ExternalBrokerUrl},

        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [securestring]
        ${RunAsPassword},

        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString}
    )
}


function Disable-SBHostCEIP() {
    [CmdletBinding()]
    param()
}


function Enable-SBHostCEIP() {
    [CmdletBinding()]
    param()
}


function Get-SBAuthorizationRule() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${Name},

        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${NamespaceName}
    )
}


function Get-SBAutoGeneratedCA() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${CACertificateFileName},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${RevocationListFileName},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString}
    )
}


function Get-SBClientConfiguration() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("ns")]
        [String[]]
        ${Namespaces}
    )
}


function Get-SBFarm() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString}
    )
}


function Get-SBFarmStatus() {
    [CmdletBinding()]
    param()
}


function Get-SBHostCEIP() {
    [CmdletBinding()]
    param()
}


function Get-SBMessageContainer() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateRange(0, 9223372036854775807L)]
        [int64]
        ${Id},

        [Parameter()]
        [switch]
        ${ShowEntities}
    )
}


function Get-SBNamespace() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("n")]
        [string]
        ${Name},

        [Parameter(Mandatory=$false,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [guid]
        ${SubscriptionId}
    )
}


function Get-SBRuntimeSetting() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateSet(
            "DefaultMaximumQueueSizeInMegabytes",
            "DefaultMaximumTopicSizeInMegabytes",
            "MaximumNumberOfConnectionsPerEntity",
            "MaximumNumberOfCorrelationFiltersPerTopic",
            "MaximumNumberOfQueuesPerNamespace",
            "MaximumNumberOfSqlFiltersPerTopic",
            "MaximumNumberOfSubscriptionsPerTopic",
            "MaximumNumberOfTopicsPerNamespace",
            "MaximumQueueSizeInMegabytes",
            "MaximumTopicSizeInMegabytes",
            "MessageCacheSizePerEntity",
            "IncludeExceptionDetails",
            "DebugMode"
        )]
        [Alias("n")]
        [string]
        ${Name}
    )
}


function Invoke-SBFarmUpgrade() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false,
                   ParameterSetName="AutoCert")]
        [ValidateNotNullOrEmpty()]
        [securestring]
        ${CertificateAutoGenerationKey},

        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString}
    )
}


function Invoke-SBHostUpgrade() {
    [CmdletBinding()]
    param()
}


function New-SBAuthorizationRule() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("n")]
        [string]
        ${Name},

        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("ns")]
        [string]
        ${NamespaceName},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            try {
                if ([Convert]::FromBase64String($_) -eq $null) {
                    return $false
                }
                return $true
            } catch [FormatException] {
                return $false
            }
        })]
        [Alias("primary")]
        [string]
        ${PrimaryKey},

        [Parameter(Mandatory=$false,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$false)]
        [Alias("rs")]
        [object[]]
        ${Rights},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            try {
                if ([Convert]::FromBase64String($_) -eq $null) {
                    return $false
                }
                return $true
            } catch [FormatException] {
                return $false
            }
        })]
        [Alias("secondary")]
        [string]
        ${SecondaryKey}
    )
}


function New-SBFarm() {
    [CmdletBinding(DefaultParameterSetName="AutoCert")]
    param(
        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [pscredential]
        ${AdminApiCredentials},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [ValidateLength(1,256)]
        [string]
        ${AdminGroup} = 'BUILTIN\Administrators',

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${AmqpPort} = 5672,

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${AmqpsPort} = 5671,

        [Parameter(Mandatory=$true,
                   ParameterSetName="AutoCert")]
        [ValidateNotNullOrEmpty()]
        [securestring]
        ${CertificateAutoGenerationKey},

        [Parameter(Mandatory=$false,
                   ParameterSetName="CustomCert")]
        [ValidateNotNullOrEmpty()]
        [string]
        ${EncryptionCertificateThumbprint},

        [Parameter(Mandatory=$true,
                   ParameterSetName="CustomCert")]
        [ValidateNotNullOrEmpty()]
        [string]
        ${FarmCertificateThumbprint},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${FarmDns},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${GatewayDBConnectionString} = ${SBFarmDBConnectionString},

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${HttpsPort} = 9355,

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65532)]
        [int32]
        ${InternalPortRangeStart} = 9000,

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${MessageBrokerPort} = 9356,

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${MessageContainerDBConnectionString} = ${SBFarmDBConnectionString},

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${RPHttpsPort} = 9359,

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${RunAsAccount} = 'servicebus@contoso',

        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString},

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${TcpPort} = 9354,

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [pscredential]
        ${TenantApiCredentials}
    )
}


function New-SBMessageContainer() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${ContainerDBConnectionString},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString}
    )
}


function New-SBNamespace() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [Alias("scheme")]
        [ValidateNotNull()]
        [string]
        ${AddressingScheme} = 1,

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${DnsEntry},

        [Parameter(Mandatory=$false,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${IssuerName},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${IssuerUri},

        [Parameter(Mandatory=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("manage")]
        [string[]]
        ${ManageUsers},

        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("n")]
        [string]
        ${Name},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            try {
                if ([Convert]::FromBase64String($_) -eq $null) {
                    return $false
                }
                return $true
            } catch [FormatException] {
                return $false
            }
        })]
        [Alias("primary")]
        [string]
        ${PrimarySymmetricKey},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            try {
                if ([Convert]::FromBase64String($_) -eq $null) {
                    return $false
                }
                return $true
            } catch [FormatException] {
                return $false
            }
        })]
        [Alias("secondary")]
        [string]
        ${SecondarySymmetricKey},

        [Parameter(Mandatory=$false,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [guid]
        ${SubscriptionId}
    )
}


function Remove-SBAuthorizationRule() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("n")]
        [string]
        ${Name},

        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("ns")]
        [string]
        ${NamespaceName}
    )
}


function Remove-SBHost() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${HostName},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString}
    )
}


function Remove-SBMessageContainer() {
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter()]
        [switch]
        ${Force},

        [Parameter(Mandatory=$true,
                   Position=0,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateRange(0, 9223372036854775807L)]
        [int64]
        ${Id}
    )
}


function Remove-SBNamespace() {
    [CmdletBinding(SupportsShouldProcess=$true)]
    param (
        [Parameter()]
        [switch]
        ${Force},

        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("n")]
        [string]
        ${Name}
    )
}


function Rename-SBAuthorizationDomain() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("n")]
        [string]
        ${Name},

        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("e")]
        [string]
        ${NewName}
    )
}


function Restore-SBEntity() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            if ($_.AbsoluteUri.EndsWith('/', $true, [CultureInfo]::CurrentCulture)) {
                return $false
            }
            if ($_.Port -ne -1) {
                return $false
            }
            return $true
        })]
        [Alias("entity")]
        [uri]
        ${EntityPath},

        [Parameter()]
        [Switch]
        ${Force},

        [Parameter(Mandatory=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("gateway")]
        [string]
        ${SourceGatewayConnectionString},

        [Parameter(Mandatory=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("containers")]
        [string[]]
        ${SourceMessageContainersConnectionStrings}
    )
}


function Restore-SBFarm() {
    [CmdletBinding(DefaultParameterSetName="AutoCert",SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [pscredential]
        ${AdminApiCredentials},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [ValidateLength(1,256)]
        [string]
        ${AdminGroup} = 'BUILTIN\Administrators',

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${AmqpPort} = 5672,

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${AmqpsPort} = 5671,

        [Parameter(Mandatory=$true,
                   ParameterSetName="AutoCert")]
        [ValidateNotNullOrEmpty()]
        [securestring]
        ${CertificateAutoGenerationKey},

        [Parameter(Mandatory=$false,
                   ParameterSetName="CustomCert")]
        [ValidateNotNullOrEmpty()]
        [string]
        ${EncryptionCertificateThumbprint},

        [Parameter(Mandatory=$true,
                   ParameterSetName="CustomCert")]
        [ValidateNotNullOrEmpty()]
        [string]
        ${FarmCertificateThumbprint},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${FarmDns},

        [Parameter()]
        [switch]
        ${Force},

        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${GatewayDBConnectionString} = ${SBFarmDBConnectionString},

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${HttpsPort} = 9355,

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65532)]
        [int32]
        ${InternalPortRangeStart} = 9000,

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${MessageBrokerPort} = 9356,

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${MessageContainerDBConnectionString} = ${SBFarmDBConnectionString},

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${RPHttpsPort} = 9359,

        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${RunAsAccount} = 'servicebus@contoso',

        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString},

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [pscredential]
        ${TenantApiCredentials}
    )
}


function Restore-SBGateway() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false,
                   ParameterSetName="AutoCert")]
        [ValidateNotNullOrEmpty()]
        [securestring]
        ${CertificateAutoGenerationKey},

        [Parameter()]
        [switch]
        ${Force},

        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${GatewayDBConnectionString},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByProperyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString}
    )
}


function Restore-SBMessageContainer() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false,
                   ParameterSetName="AutoCert")]
        [ValidateNotNullOrEmpty()]
        [securestring]
        ${CertificateAutoGenerationKey},

        [Parameter(Mandatory=$true,
                   ValueFromPipelineByProperyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${ContainerDBConnectionString},

        [Parameter()]
        [switch]
        ${Force},

        [Parameter(Mandatory=$false,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateRange(0, 9223372036854775807L)]
        [int64]
        ${Id},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByProperyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString}
    )
}


function Set-SBAuthorizationRule() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("n")]
        [string]
        ${Name},

        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("ns")]
        [string]
        ${NamespaceName},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            try {
                if ([Convert]::FromBase64String($_) -eq $null) {
                    return $false
                }
                return $true
            } catch [FormatException] {
                return $false
            }
        })]
        [Alias("primary")]
        [string]
        ${PrimaryKey},

        [Parameter(Mandatory=$false,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$false)]
        [Alias("rs")]
        [object[]]
        ${Rights},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            try {
                if ([Convert]::FromBase64String($_) -eq $null) {
                    return $false
                }
                return $true
            } catch [FormatException] {
                return $false
            }
        })]
        [Alias("secondary")]
        [string]
        ${SecondaryKey}
    )
}


function Set-SBCertificate() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false,
                   ParameterSetName="FarmAndEncryptionCert")]
        [ValidateNotNullOrEmpty()]
        [string]
        ${EncryptionCertificateThumbprint},

        [Parameter(Mandatory=$false,
                   ParameterSetName="FarmAndEncryptionCert")]
        [ValidateNotNullOrEmpty()]
        [string]
        ${FarmCertificateThumbprint},

        [Parameter(Mandatory=$false)]
        [switch]
        ${IgnoreEncryptionError},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString},

        [Parameter(Mandatory=$false)]
        [switch]
        ${SkipKeyReEncryption}
    )
}


function Set-SBCertificateAutoGenerationKey() {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false)]
        [switch]
        ${IgnoreEncryptionError},

        [Parameter(Mandatory=$true,
                   ParameterSetName="AutoCert")]
        [ValidateNotNullOrEmpty()]
        [securestring]
        ${Key},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${LastCertificateThumbprint},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString}
    )
}


function Set-SBFarm() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [pscredential]
        ${AdminApiCredentials},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [ValidateLength(1,256)]
        [string]
        ${AdminGroup},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${FarmDns},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${RunAsAccount},

        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString},

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [pscredential]
        ${TenantApiCredentials}
    )
}


function Set-SBNamespace() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${IssuerName},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${IssuerUri},

        [Parameter(Mandatory=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("manage")]
        [string[]]
        ${ManageUsers},

        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("n")]
        [string]
        ${Name},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            try {
                if ([Convert]::FromBase64String($_) -eq $null) {
                    return $false
                }
                return $true
            } catch [FormatException] {
                return $false
            }
        })]
        [Alias("primary")]
        [string]
        ${PrimarySymmetricKey},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            try {
                if ([Convert]::FromBase64String($_) -eq $null) {
                    return $false
                }
                return $true
            } catch [FormatException] {
                return $false
            }
        })]
        [Alias("secondary")]
        [string]
        ${SecondarySymmetricKey},

        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateScript({
            $guid = [Guid]::NewGuid()
            ([Guid]::TryParse($_, ([REF]$guid)))
        })]
        [Alias("subscription")]
        [string]
        ${SubscriptionId}
    )
}


function Set-SBRuntimeSetting() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [ValidateSet(
            "DefaultMaximumQueueSizeInMegabytes",
            "DefaultMaximumTopicSizeInMegabytes",
            "MaximumNumberOfConnectionsPerEntity",
            "MaximumNumberOfCorrelationFiltersPerTopic",
            "MaximumNumberOfQueuesPerNamespace",
            "MaximumNumberOfSqlFiltersPerTopic",
            "MaximumNumberOfSubscriptionsPerTopic",
            "MaximumNumberOfTopicsPerNamespace",
            "MaximumQueueSizeInMegabytes",
            "MaximumTopicSizeInMegabytes",
            "MessageCacheSizePerEntity",
            "IncludeExceptionDetails",
            "DebugMode"
        )]
        [Alias("n")]
        [string]
        ${Name},

        [Parameter(Mandatory=$true,
                   ValueFromPipeline=$true,
                   ValueFromPipelineByPropertyName=$true)]
        [ValidateNotNullOrEmpty()]
        [Alias("v")]
        [string]
        ${Value}
    )
}


function Start-SBFarm() {
    [CmdletBinding()]
    param()
}


function Start-SBHost() {
    [CmdletBinding()]
    param()
}


function Stop-SBFarm() {
    [CmdletBinding()]
    param()
}


function Stop-SBHost() {
    [CmdletBinding()]
    param()
}


function Update-SBHost() {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [securestring]
        ${CertificateAutoGenerationKey},

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [ValidateRange(1024,65535)]
        [int32]
        ${ExternalBrokerPort},

        [Parameter(Mandatory=$false)]
        [ValidateNotNull()]
        [uri]
        ${ExternalBrokerUrl},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [securestring]
        ${RunAsPassword},

        [Parameter(Mandatory=$false)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${SBFarmDBConnectionString}
    )
}


#endregion


Export-ModuleMember -Function @(
    "Add-SBHost",
    "Disable-SBHostCEIP",
    "Enable-SBHostCEIP",
    "Get-SBAuthorizationRule",
    "Get-SBAutoGeneratedCA",
    "Get-SBClientConfiguration",
    "Get-SBFarm",
    "Get-SBFarmStatus",
    "Get-SBHostCEIP",
    "Get-SBMessageContainer",
    "Get-SBNamespace",
    "Get-SBRuntimeSetting",
    "Invoke-SBFarmUpgrade",
    "Invoke-SBHostUpgrade",
    "New-SBAuthorizationRule"
    "New-SBFarm",
    "New-SBMessageContainer"
    "New-SBNamespace",
    "Remove-SBAuthorizationRule",
    "Remove-SBHost",
    "Remove-SBMessageContainer",
    "Remove-SBNamespace",
    "Set-SBAuthorizationRule",
    "Set-SBCertificate",
    "Set-SBCertificateAutoGenerationKey",
    "Set-SBFarm",
    "Set-SBNamespace",
    "Set-SBRuntimeSetting",
    "Start-SBFarm",
    "Start-SBHost",
    "Stop-SBFarm",
    "Stop-SBHost",
    "Update-SBHost"
)
